sample/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from user import views as user_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user_view.home, name="home"),
    path('', include('user.urls', namespace="user")),
    path('', include('django.contrib.auth.urls')),
    path('equipment/', include('Equipment.urls', namespace="equipment")),
    path("select2/", include("django_select2.urls")),
    path('request/', include('request.urls', namespace="request")),
]

user/urls.py
'''
     User url
'''
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import UserLoginForm

app_name = 'user'

urlpatterns = [
    path('', views.home, name='home'),

    path('login/',
         auth_views.LoginView.as_view(
              template_name="registration/login.html",
              redirect_authenticated_user=True,
              authentication_form=UserLoginForm),
         name="login"),


    path('profile/<username>',
         views.profile,
         name='profile'),

    path('profile/',
         views.user_profile,
         name='user_profile'),


    path('profile/<username>/update',
         views.update_profile,
         name="update_user"),

    path('profile/<username>/update-password',
         auth_views.PasswordChangeView.as_view(
             template_name="registration/password-change-form.html",
             success_url="/profile"),
         name="update_user_password"),

    path('admins/all-user',
         views.all_user,
         name="get_all_users"),

    path('admins/create_user',
         views.create_user,
         name="create_user"),

    path('profile/<username>/delete-user',
         views.delete_user,
         name="delete_user"),

    path('admins/reset-password/<username>',
         views.reset_password,
         name="reset_password"),

    path('admins/ban/<username>',
         views.ban_user,
         name='ban_user'),

    path('admins/unban/<username>',
         views.unban_user,
         name='unban_user'),

    path('search/<username>',
         views.unban_user,
         name='search'),
]

user/models.py
'''
    User model
'''
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    '''
        A class represent a user with extra field email and date of birth
    '''
    email = models.EmailField(max_length=200)
    date_of_birth = models.DateField(blank=True, null=True, auto_now_add=False)

    class Meta:
        db_table = "User"

    def __str__(self):
        return self.username

user/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from .models import User


class UserCreateForm(UserCreationForm):
    'User form'
    first_name = forms.CharField(required=False, max_length=200,
                                 widget=forms.PasswordInput(
                                     attrs={'class': 'form-control mb-3',
                                            'placeholder':
                                            'Enter your first name',
                                            'user-select': 'none',
                                            'id': 'first_name'}))
    last_name = forms.CharField(required=False, max_length=200,
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control mb-3',
                                           'placeholder':
                                           'Enter your last name',
                                           'user-select': 'none',
                                           'id': 'last_name'}))
    password1 = forms.CharField(max_length=200,
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control mb-3',
                                           'placeholder':
                                           'Enter your password',
                                           'user-select': 'none',
                                           'id': 'password'}))

    password2 = forms.CharField(max_length=200,
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control mb-3',
                                           'placeholder':
                                           'Enter your password',
                                           'user-select': 'none',
                                           'id': 'password2'}))

    is_superuser = forms.BooleanField(initial=False,
                                      widget=forms.CheckboxInput(),
                                      required=False)

    is_staff = forms.BooleanField(initial=False,
                                  widget=forms.CheckboxInput(),
                                  required=False)

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)
        self.fields['password1'].label = 'Enter new password'
        self.fields['password2'].label = 'Re-enter your password'

    class Meta:
        model = User

        fields = ['username', 'first_name', 'last_name',
                  'email', 'date_of_birth', 'password1',
                  'password2', 'is_superuser', 'is_staff']

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control',
                                               'placeholder':
                                                   'Enter your username',
                                               'id': 'username'}),

            'first_name': forms.TextInput(attrs={'class': 'form-control',
                                                 'placeholder': 'First Name',
                                                 'id': 'first_name',
                                                 'required': True}),

            'last_name': forms.TextInput(attrs={'class': 'form-control',
                                                'placeholder': 'Last Name',
                                                'id': 'last_name',
                                                'required': True}),

            'email': forms.TextInput(attrs={'class': 'form-control',
                                            'placeholder':
                                                'Enter your email'}),

            'date_of_birth': forms.DateInput(format=('%m %d,%y'),
                                             attrs={'class': 'form-control',
                                                    'placeholder':
                                                        'Select a date',
                                                    'type': 'date'}),

            'password1': forms.PasswordInput(attrs={'class': 'form-control',
                                                    'placeholder':
                                                        '''Enter your
                                                        password''',
                                                    'id': 'password',
                                                    'required': True}),

            'password2': forms.PasswordInput(attrs={'class': 'form-control',
                                                    'placeholder':
                                                        '''Re-enter
                                                        your password''',
                                                    'id': 're-password',
                                                    'required': True}),
        }


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(max_length=200,
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control mb-3',
                                          'placeholder': 'Enter your username',
                                          'id': 'username'}))

    password = forms.CharField(max_length=200,
                               widget=forms.PasswordInput(
                                   attrs={'class': 'form-control mb-3',
                                          'placeholder': 'Enter your password',
                                          'id': 'password'}))

    class Meta:
        model = User
        fields = ['username']
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control mb-3',
                'placeholder':
                '''Enter your username''',
                'id': 'username'}),

            'password': forms.PasswordInput(attrs={
                'class': 'form-control mb-3',
                'placeholder': '''Enter your password''',
                'id': 'password'})
        }


class UpdateUserForm(forms.ModelForm):
    'update the user information'
    email = forms.EmailField(required=False)

    class Meta:
        model = User
        fields = ["first_name", "last_name", 'email',
                  "date_of_birth"]

        widgets = {
            'date_of_birth': forms.DateInput(format=('%Y-%m-%d'),
                                             attrs={'class': 'form-control',
                                                    'placeholder':
                                                    'Select a date',
                                                    'type': 'date'}),
        }


class AdminUpdateUserForm(forms.ModelForm):
    'update the user information'
    email = forms.EmailField(required=False)

    class Meta:
        model = User
        fields = ["first_name", "last_name", 'email',
                  "date_of_birth", "is_superuser", "is_staff"]

        widgets = {
            'date_of_birth': forms.DateInput(format=('%Y-%m-%d'),
                                             attrs={'class': 'form-control',
                                                    'placeholder':
                                                    'Select a date',
                                                    'type': 'date'}),
        }


class UserUpdatePasswordForm(forms.ModelForm):
    password1 = forms.CharField(max_length=200,
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control mb-3',
                                           'placeholder':
                                           'Enter your password',
                                           'user-select': 'none',
                                           'id': 'password'}))

    password2 = forms.CharField(max_length=200,
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control mb-3',
                                           'placeholder':
                                           'Re-enter your password',
                                           'user-select': 'none',
                                           'id': 'password2'}))

    class Meta:
        model = User
        fields = ['password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(UserUpdatePasswordForm, self).__init__(*args, **kwargs)
        self.fields['password1'].label = 'Password'
        self.fields['password2'].label = 'Re-enter your password'

user/views.py
from .forms import UpdateUserForm
from .models import User
from .forms import UserCreateForm
from .forms import AdminUpdateUserForm
from .forms import UserUpdatePasswordForm
from django.shortcuts import render
from django.shortcuts import redirect
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages


def admin_required(login_url=None):
    return user_passes_test(lambda x: x.is_superuser, login_url=login_url)


def home(request):
    return render(request, 'main/main.html')


@login_required(login_url='/login')
def profile(request, username):
    get_current_user = User.objects.get(
        id=request.session.get('_auth_user_id'))
    if request.method == 'POST':
        username2 = request.POST['username']
        try:
            get_user = User.objects.get(username=username2)
        except User.DoesNotExist:
            messages.error(request, 'User not found!!!')
            return redirect('/profile/{}'.format(get_current_user.username))
    else:
        try:
            get_user = User.objects.get(username=username)
        except User.DoesNotExist:
            messages.error(request, 'User not found!!!')
            return redirect('/profile/{}'.format(get_current_user.username))
    return render(request, 'account/profile.html', {'get_user': get_user})


@login_required(login_url='/login')
def user_profile(request):
    return HttpResponseRedirect(reverse('user:profile', kwargs={
        'username': request.user.username}))


@login_required(login_url='/login')
def update_profile(request, username):
    get_user = User.objects.get(username=username)
    if request.method == 'POST':
        if request.user.is_superuser:
            form = UpdateUserForm(request.POST, instance=get_user)
        else:
            form = AdminUpdateUserForm(request.POST, instance=get_user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile have been updated successfully')
            return HttpResponseRedirect(reverse('user:get_all_users'))
        else:
            messages.error(request, '''something went wrong
                           when update the user''')
            return HttpResponseRedirect(reverse('user:get_all_users'))
    else:
        users = User.objects.all()
        if request.user.is_superuser:
            form = AdminUpdateUserForm(instance=get_user)
        else:
            form = UpdateUserForm(instance=get_user)
    return render(request, 'registration/update_profile.html',
                  {'form': form, 'users': users, 'get_user': get_user})


@login_required(login_url="/login")
def update_user_password(request, username):
    get_user = User.objects.get(username=username)
    return render(request, 'registration/password_reset.html',
                  {'get_user': get_user})


@login_required(login_url="/login")
@admin_required(login_url='/profile')
def all_user(request):
    users = User.objects.all()
    return render(request, 'admins/user.html', {'users_list': users})


@admin_required(login_url='/profile}')
@login_required(login_url="/login")
def create_user(request):
    if request.method == 'POST':
        form = UserCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'User create successfully')
            return HttpResponseRedirect(reverse('user:get_all_users'))
        else:
            messages.error(request, 'something went wrong')
            return HttpResponseRedirect(reverse('user:get_all_users'))
    else:
        form = UserCreateForm()
    return render(request, 'admins/create_user.html', {'form': form})


@admin_required(login_url='/profile')
@login_required(login_url='/login')
def delete_user(request, username):
    user = User.objects.get(username=username)
    user.delete()
    messages.warning(request, 'User delete success')
    return HttpResponseRedirect(reverse('user:get_all_users'))


def reset_password(request, username):
    get_user = User.objects.get(username=username)

    if request.method == 'POST':
        form = UserUpdatePasswordForm(request.POST, request.FILES,
                                      instance=get_user)
        if form.is_valid():
            raw_password = form.cleaned_data['password1']
            filter_password = form.cleaned_data['password2']
            if raw_password != filter_password:
                messages.error(request, 'password did not match')
                return HttpResponseRedirect(reverse('user:reset_password',
                                                    kwargs={
                                                        'username':
                                                            get_user.username}
                                                    ))
            else:
                get_user.set_password(raw_password)
                get_user.save()
                form.save()
                messages.success(request, '''User {%get_user.username%}
                             password have been reset''')
                return HttpResponseRedirect(reverse('user:get_all_users'))
        else:
            messages.error(request, 'something went wrong')
            return HttpResponseRedirect(reverse('user:get_all_users'))
    else:
        form = UserUpdatePasswordForm(instance=get_user)
    return render(request, 'registration/reset-password-form.html',
                  {'form': form, 'user': get_user})


@login_required(login_url='/login')
@admin_required(login_url='/profile')
def ban_user(request, username):
    get_user = User.objects.get(username=username)
    get_user.is_active = False
    get_user.save()
    messages.error(request, 'the user has been ban')
    return HttpResponseRedirect(reverse('user:get_all_users'))


@login_required(login_url='/login')
@admin_required(login_url='/profile')
def unban_user(request, username):
    get_user = User.objects.get(username=username)
    get_user.is_active = True
    get_user.save()
    messages.warning(request, 'the user has ben unban')
    return HttpResponseRedirect(reverse('user:get_all_users'))

user/templates/admins/create_user.html
{%extends 'main/base.html'%}

{%block title%}Create new profile {%endblock%}

{%block content%}

<div class="container">
    <div class="row pt-4">
        <p class="h4">Create new user</p>
    </div>
    <div class="row pt-2">
        <form method="post">
            {%csrf_token%}

            <div class="row mb-3">
                <div class="col mx-auto">
                    <label class="font-weight-bold">{{ form.first_name.label}}</label>
                    <div class="mt-3">
                        {{form.first_name}}
                    </div>
                </div>

                <div class="col mx-auto">
                    <label class="font-weight-bold">{{ form.last_name.label}}</label>
                    <div class="mt-3">
                        {{form.last_name}}
                    </div>
                </div>
            </div>
            <div class="mb-3 mx-auto">
                <label class="font-weight-bold">{{ form.username.label}}</label>
                <div class="mt-3">
                    {{form.username}}
                </div>
            </div>

            <div class="mb-3 mx-auto">
                <label class="font-weight-bold">{{ form.email.label}}</label>
                <div class="mt-3">
                    {{form.email}}
                </div>
            </div>

            <div class="row mb-3">
                <div class="col mx-auto">
                    <label class="font-weight-bold">{{ form.password1.label}}</label>
                    <div class="mt-3">
                        {{form.password1}}
                    </div>
                </div>

                <div class="col mx-auto">
                    <label class="font-weight-bold">{{ form.password2.label}}</label>
                    <div class="mt-3">
                        {{form.password2}}
                    </div>
                </div>
            </div>

            <div class="mb-3 mx-auto">
                <label class="font-weight-bold">{{ form.date_of_birth.label}}</label>
                <div class="mt-3">
                    {{form.date_of_birth}}
                </div>
            </div>
            {%if form.errors%}
            {{form.errors}}
            {%endif%}

            <div class="mb-5 mx-auto">
                <div class="form-check">
                    {{form.is_superuser}}
                    <label class="form-check-label" for="is_admin">
                        Create new admin
                    </label>
                </div>
                <div class="form-check">
                    {{form.is_staff}}
                    <label class="form-check-label" for="is_staff">
                        Add to staff
                    </label>
                </div>
            </div>
            <button type="submit" class="btn btn-success col-2">Create</button>
            <a href="{% url 'user:get_all_users' %}" class="btn btn-danger col-2">Cancel</a>
        </form>
    </div>
</div>
{%endblock%}

user/templates/admins/user.html
{%extends 'main/base.html'%}
{%block title%}All User {%endblock%}

{%block content%}
<style>
    small {
        font-size: smaller;
    }

    @media (min-width: 420px) and (max-width: 9999px) {

        #mytable th,
        td {
            white-space: nowrap !important;
        }
    }
</style>
<div class="container">
    <div class="row pt-5">
        <p class="h1 display-2" style="user-select:none;"> List of all user</p>
    </div>

    <div class="pt-3 mx-auto pb-1">
        <a href="{% url 'user:create_user'%}" class="btn btn-outline-success mx-auto">
            Create new user
        </a>
    </div>
    <div class="pb-2 pt-2">
        {% for message in messages %}
        <div class="container-fluid p-0">
            <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="table-responsive">
            <table class="table table-striped table-hover" id="mytable">
                <thead>
                    <tr>
                        <th scope="col" style="user-select:none;">ID</th>
                        <th scope="col" style="user-select:none;">Username</th>
                        <th scope="col" style="user-select:none;">First name</th>
                        <th scope="col" style="user-select:none;">Last name</th>
                        <th scope="col" style="user-select:none;">Email</th>
                        <th scope="col" style="user-select:none;">Date of birth</th>
                        <th scope="col" style="user-select:none;">is admin</th>
                        <th scope="col" style="user-select:none;">is staff</th>
                        <th scope="col" style="user-select:none;">is active</th>
                        <th scope="col" style="user-select:none;">Update</th>
                        <th scope="col" style="user-select:none;">Delete</th>
                        <th scope="col" style="user-select:none;">Restricted</th>
                    </tr>
                </thead>
                <tbody>
                    {%for user_m in users_list%}
                    <tr>
                        <th scope="row" style="user-select:none;">
                            <p class="d-flex justify-content-center align-content-between align-items-center">
                                {{forloop.counter}}</p>
                        </th>
                        <td style="user-select:none;">
                            <a style="text-decoration:none;"
                                href="{% url 'user:profile' user_m.username %}">{{user_m.username}}</a>
                        </td>
                        <td style="user-select:none;">
                            <p>{{user_m.first_name}}</p>
                        </td>
                        <td style="user-select:none;">
                            <p>{{user_m.last_name}}</p>
                        </td>
                        <td style="user-select:none;">
                            <p>{{user_m.email}}</p>
                        </td>
                        <td style="user-select:none;">
                            <p>{{user_m.date_of_birth}}</p>
                        </td>
                        <td>
                            {%if user_m.is_superuser%}
                            <div class="form-check mx-auto d-flex justify-content-center align-content-center">
                                <input class="form-check-input" type="checkbox" id="is_admin" disabled checked>
                            </div>
                            {%else%}
                            <div class="form-check mx-auto d-flex justify-content-center align-content-center">
                                <input class="form-check-input" type="checkbox" id="is_admin" disabled>
                            </div>
                            {%endif%}
                        </td>
                        <td>
                            {%if user_m.is_staff%}
                            <div class="form-check mx-auto d-flex justify-content-center align-content-center">
                                <input class="form-check-input" type="checkbox" id="is_admin" disabled checked>
                            </div>
                            {%else%}
                            <div class="form-check mx-auto d-flex justify-content-center align-content-center">
                                <input class="form-check-input" type="checkbox" id="is_admin" disabled>
                            </div>
                            {%endif%}
                        </td>
                        <td style="user-select:none;">
                            {%if user_m.is_active%}
                            <div class="form-check mx-auto d-flex justify-content-center align-content-center">
                                <input class="form-check-input" type="checkbox" id="is_admin" disabled checked>
                            </div>
                            {%else%}
                            <div class="form-check mx-auto d-flex justify-content-center align-content-center">
                                <input class="form-check-input" type="checkbox" id="is_admin" disabled>
                            </div>
                            {%endif%}
                        </td>
                        <td>
                            <a href="{% url 'user:update_user' user_m.username%}" class="nav-link"
                                style="text-decoration:none;user-select:none;">Update Profile</a>
                            <a href="{% url 'user:reset_password' user_m.username %}" class="nav-link"
                                style="text-decoration:none; user-select:none;">Hard Reset Password</a>
                        </td>
                        <td>
                            {%if user_m.username != user.username%}
                            <!-- Button trigger modal -->
                            <a type="button" class="btn btn-outline-warning btn-sm" data-bs-toggle="modal"
                                data-bs-target="#warningdelete{{user_m.username}}">
                                Delete User
                            </a>
                            {%endif%}
                            <!-- Modal -->
                            <div class="modal fade" id="warningdelete{{user_m.username}}" tabindex="-1"
                                data-bs-backdrop="static" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title lead fw-bold" id="exampleModalLabel"
                                                style="user-select: none;">Delete the user {{user_m.username}}?</h5>
                                        </div>
                                        <div class="modal-body">
                                            Doyou want to delete this User?
                                            <br><br>
                                            <div><small class="text-danger" style="user-select: none;"><strong>Beware:
                                                    </strong>This action will result for the user to be permarnently
                                                    delete
                                                    from the system</small></div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-outline-secondary"
                                                data-bs-dismiss="modal">Close</button>

                                            <a class="btn btn-outline-danger"
                                                href="{% url 'user:delete_user' user_m.username%}"
                                                style="text-decoration: none;">
                                                Delete
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="container">
                                {%if user_m.username != user.username%}
                                <div class="row pb-3">
                                    <a href="{%url 'user:unban_user' user_m.username%}"
                                        class="btn btn-outline-warning">Unban</a>
                                </div>
                                <div class="row pb-3">
                                    <a href="{%url 'user:ban_user' user_m.username%}"
                                        class="btn btn-outline-danger">Ban</a>
                                </div>
                                {%endif%}
                            </div>
                        </td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
        </div>
    </div>
</div>


{%endblock%}