Equipment/urls.py
"""
    Equipment url paths for view,delete,update equiment for admin
"""
from django.urls import path
from . import views

app_name = 'equipment'

urlpatterns = [
    path(r'view_all_device', views.view_all_equipment,
         name='all_equipment'),

    path(r'delete/<equipment_id>', views.delete_equip,
         name='delete_equipment'),

    path(r'update/<equipment_id>', views.update_equip,
         name='update_equipment'),

    path(r'catagory/view-all', views.view_all_catagory,
         name='view_all_catagory'),

    path(r'catagory/create', views.create_catagory,
         name='create_catagory'),

    path(r'catagory/<catagoryid>/update', views.update_catagory,
         name='update_catagory'),

    path(r'catagory/<catagoryid>/delete', views.delete_catagory,
         name='delete_catagory'),
]

sample/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from user import views as user_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user_view.home, name="home"),
    path('', include('user.urls', namespace="user")),
    path('', include('django.contrib.auth.urls')),
    path('equipment/', include('Equipment.urls', namespace="equipment")),
    path("select2/", include("django_select2.urls")),
    path('request/', include('request.urls', namespace="request")),
]

user/urls.py
'''
     User url
'''
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import UserLoginForm

app_name = 'user'

urlpatterns = [
    path('', views.home, name='home'),

    path('login/',
         auth_views.LoginView.as_view(
              template_name="registration/login.html",
              redirect_authenticated_user=True,
              authentication_form=UserLoginForm),
         name="login"),


    path('profile/<username>',
         views.profile,
         name='profile'),

    path('profile/',
         views.user_profile,
         name='user_profile'),


    path('profile/<username>/update',
         views.update_profile,
         name="update_user"),

    path('profile/<username>/update-password',
         auth_views.PasswordChangeView.as_view(
             template_name="registration/password-change-form.html",
             success_url="/profile"),
         name="update_user_password"),

    path('admins/all-user',
         views.all_user,
         name="get_all_users"),

    path('admins/create_user',
         views.create_user,
         name="create_user"),

    path('profile/<username>/delete-user',
         views.delete_user,
         name="delete_user"),

    path('admins/reset-password/<username>',
         views.reset_password,
         name="reset_password"),

    path('admins/ban/<username>',
         views.ban_user,
         name='ban_user'),

    path('admins/unban/<username>',
         views.unban_user,
         name='unban_user'),

    path('search/<username>',
         views.unban_user,
         name='search'),
]

Equipment/models.py
'''
    model for all the equipment and the request for the equipment of the user
'''
from django.db import models
from django.core.validators import validate_slug


class Catagory(models.Model):
    catagory_id = models.SlugField(verbose_name='Catagory id',
                                   primary_key=True,
                                   max_length=20,
                                   unique=True,
                                   validators=[validate_slug])
    catagory_name = models.CharField(max_length=200, blank=True)
    catagory_definition = models.CharField(max_length=200, blank=True)

    class Meta:
        db_table = 'catagory'

    def __str__(self):
        return self.catagory_id


class Equipment(models.Model):
    '''
        Equipment model
    '''
    equipment_id = models.CharField(verbose_name='Equipment id',
                                    primary_key=True,
                                    unique=True,
                                    blank=False,
                                    max_length=200)
    equipment_name = models.CharField(blank=False, max_length=200)
    equiment_description = models.TextField(blank=True, max_length=9000)
    catagory_id = models.ForeignKey(Catagory,
                                    on_delete=models.CASCADE,
                                    blank=False)
    date_obtained = models.DateTimeField(blank=True, auto_now_add=True)

    class Meta:
        db_table = 'Equipment'

    def __str__(self):
        return self.equipment_name

Equipment/forms.py
'''
    Create for for equipment borrow,
    create new equipment and update equipment information
'''
from django import forms
from .models import Equipment
from .models import Catagory


class CreateEquipment(forms.ModelForm):
    "a form for create new equipment"
    class Meta:
        "form with field id, name and equipment description"
        model = Equipment
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CreateEquipment, self).__init__(*args, **kwargs)
        self.fields['catagory_id'].label = 'Catagory'


class UpdateEquipmentInfo(forms.ModelForm):
    'a form for updating equipment information'
    class Meta:
        'a form with it name and it description'
        model = Equipment
        fields = ['equipment_name', 'equiment_description']


class CreateCatagoryForm(forms.ModelForm):
    catagory_description = forms.TextInput()

    class Meta:
        model = Catagory
        fields = '__all__'


class UpdateCatagoryForm(forms.ModelForm):

    class Meta:
        model = Catagory
        fields = '__all__'

Equipment/views.py
'''
    Creating view for all equipment
'''
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from .models import Equipment, Catagory
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test
from .forms import CreateEquipment, UpdateEquipmentInfo, CreateCatagoryForm


def admin_required(login_url=None):
    'Check if the user is super user or not and return a true or false value'
    return user_passes_test(lambda x: x.is_superuser, login_url=login_url)


@login_required(login_url='/login')
def view_all_equipment(request):
    'all user can see all the device they can borrow from the system'
    equipment = Equipment.objects.all()
    catagory = Catagory.objects.all()
    if request.method == 'POST':
        form = CreateEquipment(request.POST, request.FILES)
        equipment_id = request.POST['equip_id']
        equipment_name = request.POST['equip_name']
        equipment_description = request.POST['equip_des']
        catagory_id = request.POST['cata_id']
        try:
            Equipment.objects.get(equipment_id=equipment_id)
            messages.error(request, 'Equipment cant have same id')
        except Exception:
            if len(equipment_id) > 0 and len(equipment_name) > 0:
                new_equipment = Equipment()
                new_equipment.equipment_id = equipment_id
                new_equipment.equipment_name = equipment_name
                new_equipment.equiment_description = equipment_description
                new_equipment.catagory_id = Catagory.objects.get(
                    catagory_id=catagory_id)
                new_equipment.save()
                messages.success(request, 'Create item successfully')
            else:
                messages.error(request, 'error adding new equipment')
        return HttpResponseRedirect(reverse("equipment:all_equipment"))
    else:
        catagoryform = CreateCatagoryForm()

    return render(request, 'Equipment/viewEquipment.html',
                  {'Equipemnts': equipment,
                   'catagory': catagory, 'catagoryform': catagoryform})


@admin_required(login_url='/profile/{user.username}')
@login_required(login_url='/login')
def delete_equip(request, equipment_id):
    '''
        delete the equipment from the databases
    '''
    this_equipment = Equipment.objects.get(equipment_id=equipment_id)
    this_equipment.delete()

    messages.warning(request, 'delete successfully')
    return HttpResponseRedirect(reverse("equipment:all_equipment"))


@admin_required(login_url='/profile/{user.username}')
@login_required(login_url='/login')
def update_equip(request, equipment_id):
    get_equipment = Equipment.objects.get(equipment_id=equipment_id)
    if request.method == 'POST':
        form = UpdateEquipmentInfo(request.POST, instance=get_equipment)

        if form.is_valid():
            form.save()
            messages.success(request, 'update item successfully')
            return HttpResponseRedirect(reverse("equipment:all_equipment"))
        else:
            messages.error(request, 'something went wrong')
            return HttpResponseRedirect(reverse("equipment:all_equipment"))
    else:
        form = UpdateEquipmentInfo(instance=get_equipment)

    return render(request, 'Equipment/update_equip_info.html', {'form': form})


@login_required(login_url='/login')
def view_all_catagory(request):
    catagory_all = Catagory.objects.all()
    if request.method == "POST":
        form = CreateCatagoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'new catagory added')
            return HttpResponseRedirect(reverse())
        else:
            messages.error(request, 'Something when wrong')
            return HttpResponseRedirect(reverse())
    else:
        form = CreateCatagoryForm()
    return render(request, 'Equipment/view_all_catagory.html',
                  {"catagory_list": catagory_all,
                   "form": form})


@login_required(login_url='/login')
def update_catagory(request, catagoryid):
    catagory = Catagory.objects.get(id=catagoryid)
    return render(request, 'Equipment/update_catagory.html}')


@login_required(login_url='/login')
def delete_catagory(request, catagoryid):
    catagory = Catagory.objects.get(id=catagoryid)
    catagory.delete()
    return HttpResponseRedirect(reverse('Equipment:view_all_catagory'))


@login_required(login_url='/login')
@admin_required(login_url='/profile/{user.usææername}')
def create_catagory(request):
    if request.method == 'POST':
        form = CreateCatagoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, '''new catagory was added''')
        else:
            messages.error(request, '''Something went wrong!!!''')
        return HttpResponseRedirect(reverse('equipment:all_equipment'))
    else:
        form = CreateCatagoryForm()
    return HttpResponseRedirect(reverse('equipment:all_equipment'),
                                {'form': form})

Equipment/templates/Equipment/update_equip_info.html
{%extends 'main/base.html'%}
{%block title%} {%endblock%}

{%load crispy_forms_tags%}
{%block content%}

<div class="container">
    <div class="row">

    </div>
    <div class="row pt-5">
        <form method="POST">
            {%csrf_token%}
            {{form|crispy}}
                <button type="submit" value="" class="btn btn-outline-success">Update</button> 
                <a  href="{% url 'equipment:all_equipment' %}" class="btn btn-secondary">Cancel</a> 
        </form>
    </div>
</div>

{%endblock%}

Equipment/templates/Equipment/viewEquipment.html
{%extends 'main/base.html'%}

{%block title%}All device{%endblock%}

{%load crispy_forms_tags%}

{%block content%}
<style>
    label {
        user-select: none;
    }
</style>
<div class="container">
    <div class="row pt-5 pb-3">
        <p class="h1 notAllows">All device</p>
    </div>
    <div class="row">
        <div class="container pt-2">
            {%if user.is_superuser%}
            <!-- Button trigger device model modal -->
            <button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#deviceCreate">
                New device
            </button>

            <button class='btn btn-outline-primary' data-bs-target="#NewCata" data-bs-toggle="modal"
                data-bs-dismiss="modal">New catagory</button>
            {%endif%}

            <!-- Modal -->
            <div class="modal fade" id="deviceCreate" aria-labelledby="createDevice" data-bs-keyboard="false"
                data-bs-backdrop="static" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title notAllows" id="exampleModalLabel">New device</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <form method="POST" action="">
                                {%csrf_token%}
                                <label for="cata_ id" class="form-label notAllows">Catagory</label>
                                <select name="cata_id" id="cata_id" class="form-select form-select-lg" required>
                                    <option value=""></option>
                                    {%for cata in catagory%}
                                    <option value="{{cata.catagory_id}}">{{cata.catagory_name}}</option>
                                    {%endfor%}
                                </select>
                                <label for="equip_id" class="form-label notAllows">Equipment ID</label>
                                <input type="text" name="equip_id" id="equip_id" class="form-control"
                                    placeholder="Enter Equipment id" required />
                                <label for="equip_name" class="form-label notAllows">Equipment name</label>
                                <input type="text" name="equip_name" id="equip_name" class="form-control"
                                    placeholder="Enter Equipment name" required />
                                <label for="equip_des" class="form-label notAllows">Equipment Description</label>
                                <textarea name="equip_des" id="equip_des" class="form-control"
                                    placeholder="Enter Equipment Description" required></textarea>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-outline-secondary"
                                data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-outline-success">Save</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script>
            $('body').on('shown.bs.modal', '.modal', function () {
                $('#cata_id').select2({
                    placeholder: "Choose the device catagory",
                    dropdownParent: $('#deviceCreate'),
                    "language": {
                        "noResults": function () {
                            return `No catagory found <a class='btn btn-link'data-bs-target="#NewCata" data-bs-toggle="modal" data-bs-dismiss="modal">create new catagory?</a>`;
                        }
                    },
                    escapeMarkup: function (markup) {
                        return markup;
                    }
                });
            });
        </script>
        <div class="modal fade" data-bs-backdrop="static" id="NewCata" aria-hidden="true" tabindex="-1">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalToggleLabel2">New catagory</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="{%url 'equipment:create_catagory'%}">
                            {%csrf_token%}
                            {{catagoryform|crispy}}

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-outline-success">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Display message when client return to the html template-->
        <div class="row pt-3">
            {% for message in messages %}
            <div class="container-fluid p-0">
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
            {% endfor %}
        </div>

        <!--Display equipment list-->
        <div class="row pb-5">
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th scope="col" class="notAllows">Equipment</th>
                            <th scope="col" class="notAllows">Catagory</th>
                            <th scope="col" class="notAllows">Equiment name</th>
                            <th scope="col" class="notAllows">Equiment description</th>
                            <th scope="col" class="notAllows">Equipment register date</th>
                            {%if user.is_superuser%}
                            <th scope="col" class="notAllows">Edit Equipment</th>
                            <th scope="col" class="notAllows">Delete Equipment</th>
                            {%endif%}
                        </tr>
                    </thead>
                    <tbody class="overflow-auto">
                        {%for Equipemnt in Equipemnts%}
                        <tr>
                            <th scope="row" class="notAllows">
                                <p>{{Equipemnt.equipment_id}}</p>
                            </th>

                            <td>
                                <p>{{Equipemnt.catagory_id}}</p>
                            </td>
                            <td>
                                <p>{{Equipemnt.equipment_name}}</p>
                            </td>
                            <td>
                                <p>{{Equipemnt.equiment_description}}</p>
                            </td>
                            <td>
                                <p>{{Equipemnt.date_obtained|date:"d/m/Y"}}</p>
                            </td>
                            {%if user.is_superuser%}
                            <td>
                                <a href="{% url 'equipment:update_equipment' Equipemnt.equipment_id %}"
                                    class="notAllows">Edit
                                    Info</a>
                            </td>
                            <td>
                                <a href="{% url 'equipment:delete_equipment' Equipemnt.equipment_id %}"
                                    class="notAllows">Delete</a>
                            </td>
                            {%endif%}
                        </tr>
                        {%endfor%}
                    </tbody>
                </table>
            </div>
        </div>
        {%endblock%}