Equipment/urls.py
"""
    Equipment url paths for view,delete,update equiment for admin
"""
from django.urls import path
from . import views

app_name = 'equipment'

urlpatterns = [
    path(r'view_all_device', views.view_all_equipment,
         name='all_equipment'),

    path(r'delete/<equipment_id>', views.delete_equip,
         name='delete_equipment'),

    path(r'update/<equipment_id>', views.update_equip,
         name='update_equipment'),

    path(r'catagory/view-all', views.view_all_catagory,
         name='view_all_catagory'),

    path(r'catagory/create', views.create_catagory,
         name='create_catagory'),

    path(r'catagory/<catagoryid>/update', views.update_catagory,
         name='update_catagory'),

    path(r'catagory/<catagoryid>/delete', views.delete_catagory,
         name='delete_catagory'),
]

request/urls.py
"""
    Every user also can create a request for an equipment
"""
from django.urls import path
from .views import RequestView
from .views import CurrentReqView
from .views import PreviousReqView
from .views import ReqCreateView
from .views import AdminReqView
from .views import DeleteRequest
from .views import UpdateRequest
from .views import AdminReqView
from .views import AcceptedView
from .views import RejectView
from .views import ReturnView
app_name = 'request'

urlpatterns = [
    path('<username>/request_device',
         RequestView.as_view(template_name='request/request.html'),
         name='my_request_device'),
    path('<username>/current_request',
         CurrentReqView.as_view(template_name='request/current_request.html'),
         name='current_request'),
    path('<username>/previous_request',
         PreviousReqView.as_view(template_name='''
                                 request/previous_request.html'''),
         name='previous_request'),
    path('<username>/request',
         ReqCreateView.as_view(template_name='request/create_request.html'),
         name='create_request'),
    path('admins/request_list',
         AdminReqView.as_view(template_name='request/request_list.html'),
         name='view_request_list'),
    path('admins/<request_id>/request_accepted',
         AcceptedView,
         name='admins_accepted'),
    path('admins/<request_id>/request_rejected',
         RejectView,
         name='admins_rejected'),
    path('request/<request_id>/return',
         ReturnView,
         name='return_device'),
    path('<pk>/delete_request',
         DeleteRequest.as_view(),
         name='delete_request'),
    path('<pk>/update_request',
         UpdateRequest.as_view(template_name='request/update_request.html'),
         name='update_request'),
]

sample/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from user import views as user_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user_view.home, name="home"),
    path('', include('user.urls', namespace="user")),
    path('', include('django.contrib.auth.urls')),
    path('equipment/', include('Equipment.urls', namespace="equipment")),
    path("select2/", include("django_select2.urls")),
    path('request/', include('request.urls', namespace="request")),
]

user/urls.py
'''
     User url
'''
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import UserLoginForm

app_name = 'user'

urlpatterns = [
    path('', views.home, name='home'),

    path('login/',
         auth_views.LoginView.as_view(
              template_name="registration/login.html",
              redirect_authenticated_user=True,
              authentication_form=UserLoginForm),
         name="login"),


    path('profile/<username>',
         views.profile,
         name='profile'),

    path('profile/',
         views.user_profile,
         name='user_profile'),


    path('profile/<username>/update',
         views.update_profile,
         name="update_user"),

    path('profile/<username>/update-password',
         auth_views.PasswordChangeView.as_view(
             template_name="registration/password-change-form.html",
             success_url="/profile"),
         name="update_user_password"),

    path('admins/all-user',
         views.all_user,
         name="get_all_users"),

    path('admins/create_user',
         views.create_user,
         name="create_user"),

    path('profile/<username>/delete-user',
         views.delete_user,
         name="delete_user"),

    path('admins/reset-password/<username>',
         views.reset_password,
         name="reset_password"),

    path('admins/ban/<username>',
         views.ban_user,
         name='ban_user'),

    path('admins/unban/<username>',
         views.unban_user,
         name='unban_user'),

    path('search/<username>',
         views.unban_user,
         name='search'),
]

user/models.py
'''
    User model
'''
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    '''
        A class represent a user with extra field email and date of birth
    '''
    email = models.EmailField(max_length=200)
    date_of_birth = models.DateField(blank=True, null=True, auto_now_add=False)

    class Meta:
        db_table = "User"

    def __str__(self):
        return self.username

user/views.py
from .forms import UpdateUserForm
from .models import User
from .forms import UserCreateForm
from .forms import AdminUpdateUserForm
from .forms import UserUpdatePasswordForm
from django.shortcuts import render
from django.shortcuts import redirect
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages


def admin_required(login_url=None):
    return user_passes_test(lambda x: x.is_superuser, login_url=login_url)


def home(request):
    return render(request, 'main/main.html')


@login_required(login_url='/login')
def profile(request, username):
    get_current_user = User.objects.get(
        id=request.session.get('_auth_user_id'))
    if request.method == 'POST':
        username2 = request.POST['username']
        try:
            get_user = User.objects.get(username=username2)
        except User.DoesNotExist:
            messages.error(request, 'User not found!!!')
            return redirect('/profile/{}'.format(get_current_user.username))
    else:
        try:
            get_user = User.objects.get(username=username)
        except User.DoesNotExist:
            messages.error(request, 'User not found!!!')
            return redirect('/profile/{}'.format(get_current_user.username))
    return render(request, 'account/profile.html', {'get_user': get_user})


@login_required(login_url='/login')
def user_profile(request):
    return HttpResponseRedirect(reverse('user:profile', kwargs={
        'username': request.user.username}))


@login_required(login_url='/login')
def update_profile(request, username):
    get_user = User.objects.get(username=username)
    if request.method == 'POST':
        if request.user.is_superuser:
            form = UpdateUserForm(request.POST, instance=get_user)
        else:
            form = AdminUpdateUserForm(request.POST, instance=get_user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile have been updated successfully')
            return HttpResponseRedirect(reverse('user:get_all_users'))
        else:
            messages.error(request, '''something went wrong
                           when update the user''')
            return HttpResponseRedirect(reverse('user:get_all_users'))
    else:
        users = User.objects.all()
        if request.user.is_superuser:
            form = AdminUpdateUserForm(instance=get_user)
        else:
            form = UpdateUserForm(instance=get_user)
    return render(request, 'registration/update_profile.html',
                  {'form': form, 'users': users, 'get_user': get_user})


@login_required(login_url="/login")
def update_user_password(request, username):
    get_user = User.objects.get(username=username)
    return render(request, 'registration/password_reset.html',
                  {'get_user': get_user})


@login_required(login_url="/login")
@admin_required(login_url='/profile')
def all_user(request):
    users = User.objects.all()
    return render(request, 'admins/user.html', {'users_list': users})


@admin_required(login_url='/profile}')
@login_required(login_url="/login")
def create_user(request):
    if request.method == 'POST':
        form = UserCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'User create successfully')
            return HttpResponseRedirect(reverse('user:get_all_users'))
        else:
            messages.error(request, 'something went wrong')
            return HttpResponseRedirect(reverse('user:get_all_users'))
    else:
        form = UserCreateForm()
    return render(request, 'admins/create_user.html', {'form': form})


@admin_required(login_url='/profile')
@login_required(login_url='/login')
def delete_user(request, username):
    user = User.objects.get(username=username)
    user.delete()
    messages.warning(request, 'User delete success')
    return HttpResponseRedirect(reverse('user:get_all_users'))


def reset_password(request, username):
    get_user = User.objects.get(username=username)

    if request.method == 'POST':
        form = UserUpdatePasswordForm(request.POST, request.FILES,
                                      instance=get_user)
        if form.is_valid():
            raw_password = form.cleaned_data['password1']
            filter_password = form.cleaned_data['password2']
            if raw_password != filter_password:
                messages.error(request, 'password did not match')
                return HttpResponseRedirect(reverse('user:reset_password',
                                                    kwargs={
                                                        'username':
                                                            get_user.username}
                                                    ))
            else:
                get_user.set_password(raw_password)
                get_user.save()
                form.save()
                messages.success(request, '''User {%get_user.username%}
                             password have been reset''')
                return HttpResponseRedirect(reverse('user:get_all_users'))
        else:
            messages.error(request, 'something went wrong')
            return HttpResponseRedirect(reverse('user:get_all_users'))
    else:
        form = UserUpdatePasswordForm(instance=get_user)
    return render(request, 'registration/reset-password-form.html',
                  {'form': form, 'user': get_user})


@login_required(login_url='/login')
@admin_required(login_url='/profile')
def ban_user(request, username):
    get_user = User.objects.get(username=username)
    get_user.is_active = False
    get_user.save()
    messages.error(request, 'the user has been ban')
    return HttpResponseRedirect(reverse('user:get_all_users'))


@login_required(login_url='/login')
@admin_required(login_url='/profile')
def unban_user(request, username):
    get_user = User.objects.get(username=username)
    get_user.is_active = True
    get_user.save()
    messages.warning(request, 'the user has ben unban')
    return HttpResponseRedirect(reverse('user:get_all_users'))

user/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
{%load static%}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}Defaut title{%endblock%}</title>
    <!--bootstrap5-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!--jQuery-->
    <script src="https://code.jquery.com/jquery-3.6.2.min.js"
        integrity="sha256-2krYZKh//PcchRtd+H+VyyQoZ/e3EcrkxhM8ycwASPA=" crossorigin="anonymous"></script>

    <!--select2 framework-->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <style>
        .notAllows {
            user-select: none;
        }
    </style>
</head>

<body>

    <div class="container-fluid navbar-expand-lg navbar-dark bg-dark ">
        <div class="row pt-3">
            <div class="col-md-3">
                <div class="row">
                    <div class="col-md-4" id='home'>
                        <a href="/" class="nav-link fs-5 font-monospace text-uppercase notAllows">
                            <img id='pagepic' src="{% static 'home3.png'%}" alt="Home page pic" width="30"
                                height="auto">
                        </a>
                    </div>
                    <div class="col-md-6">
                        <ul class="navbar-nav">
                            {%if user.is_authenticated%}
                            <li class="nav-item">
                                <div class="dropdown">
                                    <a class="dropdown dropdown-toggle nav-link fs-5 font-monospace notAllows"
                                        type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown"
                                        aria-expanded="false">
                                        Device
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu dropdown-menu-dark"
                                        aria-labelledby="dropdownMenuButton1">
                                        <li><a class="dropdown-item notAllows"
                                                href="{% url 'equipment:all_equipment' %}">All
                                                device</a>
                                        </li>
                                        <li><a class="dropdown-item notAllows"
                                                href="{% url 'request:my_request_device' user.username%}">My Waiting
                                                List</a>
                                        </li>
                                        <li><a class="dropdown-item notAllows"
                                                href="{% url 'request:current_request' user.username%}">My Current
                                                Device</a>
                                        </li>
                                        <li><a class="dropdown-item notAllows"
                                                href="{% url 'request:previous_request' user.username%}">All previous
                                                Device</a>
                                        </li>
                                        <li><a class="dropdown-item notAllows"
                                                href="{% url 'request:create_request' user.username%}">Request new
                                                device</a>
                                        </li>
                                    </ul>
                                </div>
                                {%endif%}
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-7 pe-5">
                {%if user.is_authenticated%}
                <form action="{%url 'user:profile' user.username%}" method="post" class="form-inline">
                    {%csrf_token%}
                    <div class="row">
                        <div class="col-md-8">
                            <input type="text" name="username" class='form-control' placeholder="Search user">
                        </div>
                        <div class="col-md-4">
                            <input type="submit" class='btn btn-outline-light' value="Search" />
                        </div>
                    </div>
                </form>
                {%elif user.is_authenticated is not None%}
                <form class="form-inline notAllows">
                    {%csrf_token%}
                    <div class="row">
                        <div class="col-md-8">
                            <input type="text" name="username" class='form-control' placeholder="User must login">
                        </div>
                        <div class="col-md-4">
                            <a href='/login' type="button" class='btn btn-outline-light' value="Search">Search</a>
                        </div>
                    </div>
                </form>
                {%endif%}
            </div>
            <div class="col-md-2">
                <div class="row">
                    {%if user.is_authenticated and user.is_superuser%}
                    <div class="col-md-6">
                        <ul class="navbar-nav">
                            <div class="dropdown">
                                <div class="dropdown-toggle nav-link fs-5 font-monospace text-uppercase notAllows"
                                    type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                    Admin view
                                </div>
                                <ul class="dropdown-menu dropdown-menu dropdown-menu-dark"
                                    aria-labelledby="dropdownMenuButton1">
                                    <li><a class="dropdown-item notAllows" href="{% url 'user:get_all_users' %}">All
                                            user</a>
                                    </li>
                                    <li><a class="dropdown-item notAllows" href="{% url 'request:view_request_list'%}">
                                            Request
                                        </a>
                                    </li>

                                </ul>
                            </div>
                        </ul>
                    </div>
                    {%endif%}
                    <div class="col-md-6">
                        <ul class="navbar-nav">
                            {% if user.is_authenticated%}
                            <div class="dropdown">
                                <div class="dropdown-toggle nav-link fs-5 font-monospace text-uppercase notAllows"
                                    type="button" id="Profile" data-bs-toggle="dropdown" aria-expanded="false">
                                    Profile
                                </div>
                                <ul class="dropdown-menu dropdown-menu dropdown-menu-dark"
                                    aria-labelledby="dropdownMenuButton1">
                                    <li class="nav-item">
                                        <a href="{% url 'user:profile' user.username %}"
                                            class="dropdown-item nav-link fs-5 font-monospace text-uppercase notAllows">{{user.username}}</a>
                                    </li>
                                    <li><a class="dropdown-item nav-link notAllows"
                                            href="{% url 'user:update_user' user.username%}">Update
                                            Profile</a></li>
                                    <li><a href="/logout"
                                            class="dropdown-item nav-link font-monospace lh-sm notAllows">Logout</a>
                                    </li>
                                </ul>
                            </div>
                            {%else%}
                            <li class="nav-item">
                                <a href="/login" class="nav-link fs-5 font-monospace lh-sm">Log In</a>
                            </li>
                            {%endif%}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {%block content%}{%endblock%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>

user/templates/main/main.html
{%extends 'main/base.html'%}
{%block title%}Home{%endblock%}
{%block content%}


{%endblock%}