request/urls.py
"""
    Every user also can create a request for an equipment
"""
from django.urls import path
from .views import RequestView
from .views import CurrentReqView
from .views import PreviousReqView
from .views import ReqCreateView
from .views import AdminReqView
from .views import DeleteRequest
from .views import UpdateRequest
from .views import AdminReqView
from .views import AcceptedView
from .views import RejectView
from .views import ReturnView
app_name = 'request'

urlpatterns = [
    path('<username>/request_device',
         RequestView.as_view(template_name='request/request.html'),
         name='my_request_device'),
    path('<username>/current_request',
         CurrentReqView.as_view(template_name='request/current_request.html'),
         name='current_request'),
    path('<username>/previous_request',
         PreviousReqView.as_view(template_name='''
                                 request/previous_request.html'''),
         name='previous_request'),
    path('<username>/request',
         ReqCreateView.as_view(template_name='request/create_request.html'),
         name='create_request'),
    path('admins/request_list',
         AdminReqView.as_view(template_name='request/request_list.html'),
         name='view_request_list'),
    path('admins/<request_id>/request_accepted',
         AcceptedView,
         name='admins_accepted'),
    path('admins/<request_id>/request_rejected',
         RejectView,
         name='admins_rejected'),
    path('request/<request_id>/return',
         ReturnView,
         name='return_device'),
    path('<pk>/delete_request',
         DeleteRequest.as_view(),
         name='delete_request'),
    path('<pk>/update_request',
         UpdateRequest.as_view(template_name='request/update_request.html'),
         name='update_request'),
]

sample/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from user import views as user_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user_view.home, name="home"),
    path('', include('user.urls', namespace="user")),
    path('', include('django.contrib.auth.urls')),
    path('equipment/', include('Equipment.urls', namespace="equipment")),
    path("select2/", include("django_select2.urls")),
    path('request/', include('request.urls', namespace="request")),
]

user/urls.py
'''
     User url
'''
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import UserLoginForm

app_name = 'user'

urlpatterns = [
    path('', views.home, name='home'),

    path('login/',
         auth_views.LoginView.as_view(
              template_name="registration/login.html",
              redirect_authenticated_user=True,
              authentication_form=UserLoginForm),
         name="login"),


    path('profile/<username>',
         views.profile,
         name='profile'),

    path('profile/',
         views.user_profile,
         name='user_profile'),


    path('profile/<username>/update',
         views.update_profile,
         name="update_user"),

    path('profile/<username>/update-password',
         auth_views.PasswordChangeView.as_view(
             template_name="registration/password-change-form.html",
             success_url="/profile"),
         name="update_user_password"),

    path('admins/all-user',
         views.all_user,
         name="get_all_users"),

    path('admins/create_user',
         views.create_user,
         name="create_user"),

    path('profile/<username>/delete-user',
         views.delete_user,
         name="delete_user"),

    path('admins/reset-password/<username>',
         views.reset_password,
         name="reset_password"),

    path('admins/ban/<username>',
         views.ban_user,
         name='ban_user'),

    path('admins/unban/<username>',
         views.unban_user,
         name='unban_user'),

    path('search/<username>',
         views.unban_user,
         name='search'),
]

request/models.py
from django.db import models

from user.models import User
from Equipment.models import Equipment

# Create your models here.


class Request(models.Model):
    '''
        Create user request for equipment connect to 2 table user and equipment
    '''
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name="User_request")
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    date_created = models.DateTimeField(blank=False, auto_now_add=True)
    expect_return_date = models.DateTimeField(blank=True)
    reason = models.TextField(max_length=1000, null=True, blank=True)
    date_return = models.DateTimeField(blank=True, null=True)
    approval = models.IntegerField(default=0)
    approval_admin = models.ForeignKey(User, on_delete=models.CASCADE,
                                       related_name="Admin_request",
                                       null=True, blank=True)

    class Meta:
        db_table = 'request'

    def __str__(self):
        return "{} request {}".format(self.user, self.equipment)

request/forms.py
from django import forms
from .models import Request
from django_select2.forms import Select2Widget


class NewRequestForm(forms.ModelForm):
    class Meta:
        model = Request
        fields = ['equipment', 'expect_return_date',
                  'reason']
        widgets = {
            'equipment': Select2Widget,
            'expect_return_date': forms.DateInput(format=("%Y-%m-%d"),
                                                  attrs={
                                                      'class': 'form-control',
                                                      'placeholder':
                                                          'Select a date',
                                                          'type': 'date'}),
        }

request/views.py
from .models import Request
from .forms import NewRequestForm
from django.urls import reverse
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import HttpResponseRedirect
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.decorators import login_required
from django.utils import timezone


def admin_required(login_url=None):
    return user_passes_test(lambda x: x.is_superuser, login_url=login_url)


class SuperUser(UserPassesTestMixin, LoginRequiredMixin):
    """
    Check user if the user is a superuser or not in CBV
    """

    def test_func(self):
        return self.request.user.is_superuser


class RequestView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = ''
    model = Request
    context_object_name = 'request_list'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context

    def get_queryset(self):
        queryset = super(RequestView, self).get_queryset()
        return queryset.filter(user=self.request.user.id, approval=False)

    def get(self, request, *args, **kwargs):
        user_request = self.get_queryset()
        return render(request, 'request/request.html',
                      {'request_list': user_request})


class CurrentReqView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = ''
    model = Request
    context_object_name = 'current_request'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context

    def get_queryset(self):
        queryset = super(CurrentReqView, self).get_queryset()
        return queryset.filter(user=self.request.user.id, approval=True,
                               date_return=None)

    def get(self, request, *args, **kwargs):
        user_request = self.get_queryset()
        return render(request, 'request/my_request.html',
                      {'current_request': user_request})


class PreviousReqView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = ''
    model = Request
    context_object_name = 'previous_request'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context

    def get_queryset(self):
        queryset = super(PreviousReqView, self).get_queryset()
        return queryset.filter(user=self.request.user.id)

    def get(self, request, *args, **kwargs):
        user_request = self.get_queryset()
        return render(request, 'request/previous_request.html',
                      {'previous_request': user_request})


class ReqCreateView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = ''
    model = Request
    form_class = NewRequestForm

    def get_success_url(self, **kwargs):
        return reverse('request:my_request_device',
                       kwargs={
                           'username': self.request.user
                       })

    def get(self, request, *args, **kwargself):
        return render(request, 'request/create_request.html',
                      {'form': self.form_class, 'user': self.request.user})

    def form_valid(self, form):
            
        form.instance.user = self.request.user
        if self.request.user.is_superuser:
            form.instance.approval = 1
            form.instance.approval_admin = self.request.user
        form.instance = form.save()
        messages.success(self.request, "your request has been send")
        return super(ReqCreateView, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "some thing went wrong")
        return self.get_success_url()


class AdminReqView(SuperUser, ListView):
    model = Request
    login_url = '/login'
    redirect_field_name = ''
    context_object_name = 'request_list_all'

    def get_success_url(self):
        return reverse('request:view_request_list')

    def get_queryset(self):
        queryset = super(AdminReqView, self).get_queryset()
        return queryset.filter(approval=False)


class DeleteRequest(LoginRequiredMixin, DeleteView):
    model = Request
    login_url = '/login/'
    redirect_field_name = ''
    model = Request

    def get_success_url(self, **kwargs):
        messages.error(self.request, '''your request
                       has been deleted ''')
        return reverse('request:my_request_device', kwargs={
            'username': self.request.user})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)


class UpdateRequest(LoginRequiredMixin, UpdateView):
    model = Request
    login_url = '/login/'
    redirect_field_name = ''
    model = Request
    form_class = NewRequestForm

    def get_success_url(self):
        messages.success(self.request, '''request have been
                         updated successfully''')
        return reverse('request:my_request_device',
                       kwargs={
                           'username': self.request.user
                       })

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().get(request, *args, **kwargs)


@admin_required(login_url='/profile}')
@login_required(login_url="/login")
def RejectView(request, request_id):
    this_request = Request.objects.get(id=request_id)
    this_request.approval = -1
    this_request.save()
    print(Request.objects.get(id=this_request.id).approval)
    messages.SUCCESS(request, 'you have accepted the request')
    return HttpResponseRedirect(reverse('request:view_request_list'))

@admin_required(login_url='/profile}')
@login_required(login_url="/login")
def AcceptedView(request, request_id):
    this_request = Request.objects.get(id=request_id)
    this_request.approval_admin = request.user
    this_request.approval = True
    this_request.save()
    messages.success(request, 'you have accepted the request')
    return HttpResponseRedirect(reverse('request:view_request_list'))



@login_required(login_url="/login")
def ReturnView(request, request_id):
    this_request = Request.objects.get(id=request_id)
    this_request.date_return = timezone.now()
    this_request.save()
    messages.success(request, 'you have accepted the request')
    return HttpResponseRedirect(reverse('request:current_request',
                                        kwargs={'username': request.user}))

request/templates/request/create_request.html
{%extends 'main/base.html'%}

{%load crispy_forms_tags%}
{%block content%}
<div class="container">
    <div class="row pt-5 pb-5 user-select-none">
        <p class="lead display-3">
            Create new request
        </p>
    </div>
    <div class="row">
        <div class="col-md-6">
            <form method="post">
                {%csrf_token%}
                {{form|crispy}}
                <button type="submit" class="btn btn-outline-success">Submit</button>
                <a class="btn btn-outline-secondary" href="{%url 'request:current_request' user.username%}">Cancel</a>
            </form>
        </div>
        <div class="col-md-6">
            <div class="card" style="width: 18rem;">
                <div class="card-body user-select-none">
                    <h5 class="card-title">Request Policy</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Apply to all employees</h6>
                    <p class="card-text">The Company will retain Your Personal Data only for as long as is necessary for
                        the purposes set out in this Privacy Policy.
                        card's content.</p>
                    <p class="card-text">Your information, including Personal Data, is processed at the Company's
                        operating offices and in any other places where the parties involved in the processing are
                        located.</p>
                    <p class="card-text">
                        If you have any questions about this Policy, You can contact us:<br>
                        <strong class="user-select-auto"> admin@admin.com</strong>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{{ form.media.js }}
{%endblock%}

request/templates/request/my_request.html
{%extends 'main/base.html'%}

{%block title%}All device{%endblock%}

{%load crispy_forms_tags%}

{%block content%}
<div class="container">
    <div class="row pt-5 pb-3">
        <p class="display-4 lead user-select-none">Current request</p>
    </div>
    <div class="row">
        <div>
            <a href="{%url 'request:previous_request' user.username%}" class="btn btn-outline-success col-md-2">My
                previous request</a>
            <a href="{%url 'request:create_request' user.username%}" class="btn btn-outline-primary col-md-2">Create
                new request</a>
        </div>
        <div class="table-responsive">
            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th class="notAllows" scope="col">#</th>
                        <th class="notAllows" scope="col">Equipment id</th>
                        <th class="notAllows" scope="col">Equipment</th>
                        <th class="notAllows" scope="col">Equipment description</th>
                        <th class="notAllows" scope="col">Date Create</th>
                        <th class="notAllows" scope="col">Expected Return</th>
                        <th class="notAllows" scope="col">Reason</th>
                        <th class="notAllows" scope="col">Approve</th>
                        <th class="notAllows" scope="col">Approve by</th>
                        <th class="notAllows" scope="col">Return</th>
                    </tr>
                </thead>
                <tbody>
                    {%for request in current_request%}
                    <tr>
                        <th scope="row" class="notAllows"> {{forloop.counter}}</th>
                        <td>{{request.equipment_id}}</td>
                        <td>{{request.equipment.equipment_name}}</td>
                        <td>{{request.equipment.equiment_description}}</td>
                        <td>{{request.date_created|date:"d/m/Y"}}</td>
                        <td>{{request.expect_return_date|date:"d/m/Y"}}</td>
                        <td>{{request.reason}}</td>
                        <td>
                            {%if request.approval == 0%}
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red"
                                class="bi bi-x-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                <path
                                    d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                            </svg>
                            {%endif%}
                            {%if request.approval == 1%}
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="green"
                                class="bi bi-check-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                <path
                                    d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z" />
                            </svg>
                            {%endif%}
                        </td>
                        <td>
                            {{request.approval_admin}}
                        </td>
                        <td>
                            <a href="{%url 'request:return_device' request.id%}" class="btn btn-outline-danger">Return</a>
                        </td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
        </div>
    </div>
</div>
{%endblock%}

request/templates/request/previous_request.html
{%extends 'main/base.html'%}

{%block title%}All device{%endblock%}

{%load crispy_forms_tags%}

{%block content%}
<div class="container">
    <div class="row pt-5 pb-3">
        <p class="display-4 lead user-select-none">Previous request</p>
    </div>
    <div class="row">
        <div>
            <a href="{%url 'request:current_request' user.username%}" class="btn btn-outline-secondary col-md-2">My
                current request</a>
        </div>
        <div class="table-responsive">
            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th class="notAllows" scope="col">#</th>
                        <th class="notAllows" scope="col">Equipment</th>
                        <th class="notAllows" scope="col">Date Create</th>
                        <th class="notAllows" scope="col">Expected Return</th>
                        <th class="notAllows" scope="col">Reason</th>
                        <th class="notAllows" scope="col">Approve by</th>
                        <th class="notAllows" scope="col">Return date</th>
                        <th class="notAllows" scope="col">Approve</th>
                    </tr>
                </thead>
                <tbody>
                    {%for request in previous_request%}
                    <tr>
                        <th scope="row" class="notAllows"> {{forloop.counter}}</th>
                        <td>{{request.equipment_id}}</td>
                        <td>{{request.date_created|date:"d/m/Y"}}</td>
                        <td>{{request.expect_return_date|date:"d/m/Y"}}</td>
                        <td>{{request.reason}}</td>
                        <td>
                            {{request.approval_admin}}
                        </td>
                        <td>
                            {%if request.date_return is None and request.approval_admin is not None%}
                            Not return yet!
                            {%elif request.date_return is None and request.approval_admin is None%}
                            <div class="col-md-5"> Not allows to borrow</div>
                            {%endif%}
                            {{request.date_return|date:'d/m/Y'}}
                        </td>
                        <td>
                            {%if request.approval == -1%}
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red"
                                class="bi bi-x-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                <path
                                    d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                            </svg>
                            {%endif%}
                            {%if request.approval == 0%}
                                Pendning...
                            {%endif%}
                            {%if request.approval == 1%}
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="green"
                                class="bi bi-check-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                <path
                                    d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z" />
                            </svg>
                            {%endif%}
                        </td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
        </div>
    </div>
</div>
{%endblock%}

request/templates/request/request.html
{%extends 'main/base.html'%}

{%block title%}All device{%endblock%}

{%load crispy_forms_tags%}

{%block content%}
<div class="container">
    <div class="row pt-5 pb-3">
        <p class="display-4 lead user-select-none">Waiting request</p>
    </div>
    <div class="row pt-3">
        {% for message in messages %}
        <div class="container-fluid p-0">
            <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="row">
        <div>
            <a href="{%url 'request:create_request' user.username%}" class="btn btn-outline-success col-md-2">Create
                new request</a>
            <a href="{%url 'request:current_request' user.username%}" class="btn btn-outline-primary col-md-2">My
                current Request</a>
        </div>
        <div class="table-responsive">
            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th class="notAllows" scope="col">#</th>
                        <th class="notAllows" scope="col">Equipment</th>
                        <th class="notAllows" scope="col">Date Create</th>
                        <th class="notAllows" scope="col">Expected Return</th>
                        <th class="notAllows" scope="col">Reason</th>
                        <th class="notAllows" scope="col">Approve</th>
                        <th class="notAllows" scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {%for request in request_list%}
                    <tr>
                        <th scope="row" class="notAllows"> {{forloop.counter}}</th>
                        <td>{{request.equipment_id}}</td>
                        <td>{{request.date_created|date:"d/m/Y"}}</td>
                        <td>{{request.expect_return_date|date:"d/m/Y"}}</td>
                        <td>{{request.reason}}</td>
                        <td>
                            {%if request.approval == -1%}
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red"
                                class="bi bi-x-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                <path
                                    d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                            </svg>
                            {%endif%}
                            {%if request.approval == 0%}
                            <P>Pending ...</P>
                            {%endif%}
                            {%if request.approval == 1%}
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="green"
                                class="bi bi-check-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                <path
                                    d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z" />
                            </svg>
                            {%endif%}
                        </td>
                        <td>
                            <div class="d-flex flex-column">
                                    <a class="btn btn-outline-warning form-control" href="{%url 'request:update_request' request.id%}">Edit</a>
                                <div class="row">
                                    <form action="{%url 'request:delete_request' request.id%}" method="post">
                                        {%csrf_token%}
                                        <button class="btn btn-outline-danger form-control">Cancel Request</button>
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
        </div>
    </div>
</div>
{%endblock%}

request/templates/request/request_list.html
{%extends 'main/base.html'%}

{%block content%}
<div class="container">
    <div class="row">
        User request list
    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                    <tr class="user-select-none">
                        <th scope="col">#</th>
                        <th scope="col">Request User</th>
                        <th scope="col">Catagory</th>
                        <th scope="col">Equipment</th>
                        <th scope="col">Reason</th>
                        <th scope="col">Expected return date</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {%for request in request_list_all%}
                    <tr>
                        <th scope="row" class="user-select-none">{{forloop.counter}}</th>
                        <td>{{request.user}}</td>
                        <td>{{request.equipment.catagory_id}}</td>
                        <td>{{request.equipment}}</td>
                        <td>{{request.reason}}</td>
                        <td>{{request.expect_return_date|date:'d/m/Y'}}</td>
                        <td>
                            <a class='btn btn-outline-danger' href="{%url 'request:admins_rejected' request.id%}">Decline</a>
                            <a class='btn btn-outline-success' href="{%url 'request:admins_accepted' request.id%}">Accepted</a>
                        </td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
        </div>
    </div>
</div>
{%endblock%}

request/templates/request/update_request.html
{%extends 'main/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
<div class="container">
    <div class="row">
        <div class="lead display-1 user-select-none pt-5 pb-5">Update request</div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form method="post" action="{%url 'request:update_request' request.id%}">
                {%csrf_token%}
                {{form|crispy}}
                <input type="submit" value='Save change' class='btn btn-outline-success'>
                <a href="{%url 'request:my_request_device' user.username%}" class='btn btn-outline-secondary'>Cancel</a>
            </form>
        </div>
    </div>
</div>
{%endblock%}